version: "3.5"
services:
  cellxgene:
    image: ${CELLXGENE_IMAGE}
    container_name: cellxgene
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf.d:/etc/nginx/sites-available/
      - ../certs/:/certs
      - ./data/:/test-files/
    env_file:
      - .env